### ISSUE TITLE
h5 files written as 3D data sets

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#103]
The new header4D Camera version4 datasets (in sector format) need to be recombined into full images in an H5 file. This file is a 3D dataset rather than a 4D dataset. Can this be changed to make analysis easier?

Here is the code to take raw output files from the camera an make them into H5 files.
```python
h5Path = (dataset_path / Path('scan{}.h5'.format(dataset_num)))
reader = io.reader(files, version=io.FileVersion.VERSION4)
io.write_hdf5(str(h5Path), reader)
```

**Comment by cjh1** [comment]
You want the scan shape as the first dimension? I think the reason we separated it out in the current format is so that the scan positions could be looked up independently in another data set ( scan_positions ), I think we where thinking about the possibility that format could support part of a scan. However, we can certainly look a changing this for this use case.

**Comment by cjh1** [comment]
This is now supported in master, by specifying the `format` named parameter.
