### ISSUE TITLE
SparseArray updates

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#203]
Im starting to use the sparse array class and Ill keep track of some issues I find as I go

1. using negative indexing works except for [-1, -1] to get the last pattern. The error is `ValueError: cannot select an axis to squeeze out which has size not equal to one`
2.  I very often us the ravel() function to make it easy to iterate over a multidimensional array. Can this function be made to return a raveled version along the scan dimensions?
3. SparseArray.reshape says that it takes a tuple, but if you send it a tuple then you get an error. You need to use `.reshape(a, b, c)` not .`reshape((a, b, c))`
4.  The scan dimensions are backwards compared to what stempy.io.load_electrons() returns. I have to use 
```python
electron_events = stio.load_electron_counts(str(fname))
sp = SparseArray(electron_events.data, electron_events.scan_dimensions[::-1], electron_events.frame_dimensions)
```
to get the correct shape. This is part of the confusion I have with scan_dimensions being backwards in some cases.

**Comment by psavery** [comment]
Hi @ercius, thank you for reporting these issues. I am going to look into them soon, and add a few tests as well for the `SparseArray` so we can have a stronger guarantee of reliability.

**Comment by ercius** [comment]
Another quick issue possibly relate to 1. above:
5. If I slice outside the size of the array then I get a weird error message:
`ValueError: cannot select an axis to squeeze out which has size not equal to one`
This should be an `IndexError` instead.

**Comment by ercius** [comment]
Another:
6. If I slice and sum in a way that makes one of the axes singular then I get an error that it needs to expand fully. But the sum should be over the sparse axis and there is no need for expansion
throws error:
`data[0, 0:1, :, :].sum(axis=(0,1))`
`data[0:1, 0:1, :, :].sum(axis=(0,1))`
no error
`data[0:2,0:2,:,:].sum(axis=(0,1))`
`data[0, 0, :, :].sum(axis=(0,1))`

**Comment by psavery** [comment]
Hi @ercius, I have fixed numbers 1, 3, and 5 in #205, along with a few other issues that I encountered. That PR also adds some fairly thorough testing to make it easier to develop (to ensure nothing breaks when we make changes).

I have a few questions/comments about the other ones:

> 2. I very often us the ravel() function to make it easy to iterate over a multidimensional array. Can this function be made to return a raveled version along the scan dimensions?

Sure. I believe the `SparseArray` class should work with a flat scan dimension (for instance, you can reshape `(50, 50, 576, 576)` into `(2500, 576, 576)`, and I think it should work). Should I add a function called something like `ravel_scans()` to do this automatically and reshape it so the scan dimension is 1D?

> 4. The scan dimensions are backwards compared to what stempy.io.load_electrons() returns. I have to use
> 
> ```python
> electron_events = stio.load_electron_counts(str(fname))
> sp = SparseArray(electron_events.data, electron_events.scan_dimensions[::-1], electron_events.frame_dimensions)
> ```
> 
> to get the correct shape. This is part of the confusion I have with scan_dimensions being backwards in some cases.

Hmm, we can perhaps change the index raveling that is being done internally. It currently matches the behavior of numpy. For instance, indexing `[1, 2]` into a shape of `(3, 5)` vs `(5, 3)`:
```python
>>> np.ravel_multi_index((1, 2), (5, 3))
5
>>> 1 * 3 + 2
5
>>> np.ravel_multi_index((1, 2), (3, 5))
7
>>> 1 * 5 + 2
7
```

Essentially, for indices `i`, `j`, and shape `shape`, the raveling operation in numpy is `i * shape[1] + j`, which is being done [here](https://github.com/OpenChemistry/stempy/blob/3b2d25c20ac92e357249eb8d89abb4b6e06c2245/python/stempy/io/sparse_array.py#L451), for instance. Should we try to change it to be `i * shape[0] + j` instead?

> Another:
> 6. If I slice and sum in a way that makes one of the axes singular then I get an error that it needs to expand fully. But the sum should be over the sparse axis and there is no need for expansion
> throws error:
> `data[0, 0:1, :, :].sum(axis=(0,1))`
> `data[0:1, 0:1, :, :].sum(axis=(0,1))`
> no error
> `data[0:2,0:2,:,:].sum(axis=(0,1))`
> `data[0, 0, :, :].sum(axis=(0,1))`

So, there was some inconsistent behavior about singular axes in the `SparseArray` that is fixed in #205. Now it matches the behavior of numpy, which is essentially: indexing removes axes, and slicing retains axes. For instance:

```python
>>> import numpy as np
>>> a = np.arange(25).reshape(5, 5)
>>> a.shape
(5, 5)
>>> a[0:1, :].shape
(1, 5)
>>> a[0, :].shape
(5,)
```

You can see that indexing into it removes the axis, but slicing into it retains the axis.

This behavior is now reflected in #205. I should also mention that the `SparseArray` takes into
account whether the scan dimension is 2D or 1D. So, for instance, `data[0, 0:1, :, :].shape` will be `(1, 576, 576)`, 
so if you want to perform a sum after slicing, you should do `.sum(axis=0)` to specify the single scan axis, rather
than `.sum(axis=(0, 1))`. I should note also that if you remove both scan axes via indexing, such as `data[0, 0, :, :]`,
it no longer returns a `SparseArray`, but a numpy array. So this would return a numpy array of shape `(576, 576)`,
and performing a sum on it would just be performing a sum on a numpy array.

The other sum examples are [here](https://github.com/OpenChemistry/stempy/pull/205/files#diff-c69697daff33b674839296ec40cdc2a75ece3c69b67899eca991735ccdfd4cadR296-R303) in case you'd like to see them,
and how the axis changes depending on the slicing operation.

**Comment by ercius** [comment]
> Should I add a function called something like ravel_scans() to do this automatically and reshape it so the scan dimension is 1D?

Yes. I think this function would be very useful. The name is good too.

> Should we try to change it to be i * shape[0] + j instead?

I think this is a bigger conversation, because it seems to me that the indexing in other stempy functions is backwards from numpy as I show in my example. However, this does show that we need a way to pass a electron counted stempy NamedTuple directly into the sparsearray class and a way to load sparse data from a stempy HDF5 file directly. Then there is no ambiguity when loading or converting data.

> So, there was some inconsistent behavior about singular axes in the SparseArray that is fixed in #205.

This is a good way to go. I think making the class work as close to a numpy dense ndarray is the desired functionality. 

If you can implement the ravel_scans() and the data loading/conversion then we are close to done!

**Comment by psavery** [comment]
@ercius Sounds good, I have added both of those to #205.

Note that the `ravel_scans()` and `reshape()` functions reshape the array in place (and returns the array), unlike numpy which returns a new view of the array that is reshaped (and the original array's shape is unmodified). This is because we don't have views of SparseArrays like `np.ndarray.view` in numpy.

With #205, you can create a `SparseArray` like the following:
```python
array = SparseArray.from_electron_counts(electron_counts)

array = SparseArray.from_hdf5(filepath)
```

You can also pass in any kwargs you want forwarded to the `SparseArray.__init__()` method, like the dtype:
```python
array = SparseArray.from_hdf5(filepath, dtype=np.uint64)
```

**Comment by ercius** [comment]
Excellent improvements. Thanks!

**Comment by psavery** [comment]
@ercius This is now merged to master.
