### ISSUE TITLE
SparseArray.sum() slower than calculate_sum_sparse

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#221]
It looks like the SparseArray() class sum() operator is 2x slower than the stempy.image.calculate_sum_sparse() operation. Can we look into speeding the SparseArray class up to improve performance?

**Comment by psavery** [comment]
Hi Peter. I believe the reason `SparseArray.sum()` is slower than `calculate_sum_sparse()` is that `SparseArray.sum()` [uses `np.unique()`](https://github.com/OpenChemistry/stempy/blob/4f8ddeb5b089c5ac2d634cb348cee5113df506a3/python/stempy/io/sparse_array.py#L333-L337) so that it can take into account duplicates in the sparse frame, whereas [`calculate_sum_sparse()` does not](https://github.com/OpenChemistry/stempy/blob/4f8ddeb5b089c5ac2d634cb348cee5113df506a3/python/stempy/image/__init__.py#L570-L574). Taking into account duplicates was especially important for binning, because that often produces sparse frames with duplicate values.

For instance. If you count a single 2x2 sparse frame `[0, 2, 2]`, and you use `calculate_sum_sparse()`, you will get this:
```python
[[ 1, 0 ],
 [ 1, 0 ]]
```

Whereas, if you use `SparseArray.sum()`, you will get this:
```python
[[ 1, 0 ],
 [ 2, 0 ]]
```

That being said, we may still be able to figure out ways to speed up `SparseArray.sum()` using tools like [numba](https://numba.pydata.org/), but I'm not sure how long it will take.

Also alternatively, we could add an option to the `SparseArray` class to indicate whether it should take into account duplicates, and it can use different implementations of its functions depending on whether it needs to take into account duplicates or not. I believe all of the math operations and expanding could have faster implementations that do not take into account duplicates.

**Comment by ercius** [comment]
@psavery You are right! I thought I had written `stempy.image.calculate_sum_sparse()` to properly take mutiple electrons into account, but its written incorrectly. We only get 1 electron per probe position with `stempy.image.calculate_sum_sparse()` if there were multiple frames acquired. It needs two `for` loops and then its much slower than the `SparseArray` implementation. Ill submit a pull request to fix this problem, but I think we should just switch to `SparseArray` anyway.

We should implement #208 which would then allow us to speed everything up by assuming each probe position has only 1 electron per detector pixel.
