### ISSUE TITLE
add SparseArray.to_hdf5()

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#229]
It would be very useful to be able to save a sparse array to an HDF5 file by `SparseArray.to_hdf5()` properly formatted such that it can be read again with `from_hdf5()`.

Reasons for this are for example cropping or binning data and then saving to disk to load again later.

**Comment by psavery** [comment]
Hi @ercius,

I believe the [SparseArray.write_to_hdf5()](https://github.com/OpenChemistry/stempy/blob/3d1ad2b8ab9f144eb4bb0e5489646ae2a60720d7/python/stempy/io/sparse_array.py#L146) function does this. In fact, the [save/load electron counts functions](https://github.com/OpenChemistry/stempy/blob/3d1ad2b8ab9f144eb4bb0e5489646ae2a60720d7/python/stempy/io/__init__.py#L158-L177) are calling these functions underneath.

We also have a [test running](https://github.com/OpenChemistry/stempy/blob/3d1ad2b8ab9f144eb4bb0e5489646ae2a60720d7/tests/test_sparse_array.py#L331-L348) as well that writes a SparseArray to HDF5 and then reads it back in, confirming that it is the same.

Please let me know if you'd prefer the name `to_hdf5()` instead of `write_to_hdf5()`, or if any other changes are needed.

**Comment by ercius** [comment]
This is exactly what I was asking for. Not sure how I missed it. Thanks!

**Comment by cjh1** [comment]
@ercius I think we need to push a new version, I don't think they are in a release but @psavery can confirm that. We have made some breaking changes to the API so need to increment the major version, so I was holding off until we have merged a few more PRs.

**Comment by cjh1** [comment]
@ercius I pushed a pre release tag for 2.0.0 ( 2.0.0.a1 ). It should include the changes you are after. You can install this version for testing using:

```
pip install --pre stempy
```

Once we have merged a few more PR I will cut 2.0.0 and put up some release notes to explain the breaking change.

**Comment by ercius** [comment]
ok. no problem! Thanks for the pre-release. I can use that until everything is finalized.
