### ISSUE TITLE
slicing time increases as row number increases

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#246]
I see a strange behavior when Im trying to slice in the sparse domain to operate on all frames at a single scan position while keeping the data as sparse. I want to avoid densifying the data (i.e. `experiment[ii,jj,:,:]`)

Here is the obvious way to do this, but it get slower and slower:
```python
my_time = []
for ii in range(10):
    for jj in range(10):
        tt0 = time.time()
        single_sparse = experiment[ii:ii+1,jj:jj+1,:,:] # get all sparse frames at a single position; keep as a sparse array
        my_time.append(time.time() - tt0)
plt.figure()
plt.plot(my_time)
```
![Figure 33](https://user-images.githubusercontent.com/15657108/160250715-cf0bc402-5a1f-4c37-8057-6c8f0cf8e5ec.png)

This increases into the many seconds per slice operation making operations on average sized data sets extremely slow.

If I instead slice each row before the second for loop the performance is consistent
```python
my_time = []
for ii in range(10):
    row = experiment[ii,:,:,:]
    for jj in range(10):
        tt0 = time.time()
        single_sparse = row[jj:jj+1,:,:]
        my_time.append(time.time() - tt0)
plt.figure()
plt.plot(my_time)
```
![Figure 32](https://user-images.githubusercontent.com/15657108/160250750-25938691-e50c-453f-b376-d074b57ec792.png)

This behavior should be changed so that slicing a single position has the same performance no matter where this is done in real space.

**Comment by cjh1** [comment]
@psavery Can you take a look at this?

**Comment by ercius** [comment]
I looked at the slicing algorithm and I might have a faster way to do it. It would be good to discuss first.

**Comment by psavery** [comment]
Hi @ercius. I was able to reproduce the issue with a large dataset and large scan positions, where it would take more than a second to perform the sparse slicing. I also narrowed the issue to [these lines of code](https://github.com/OpenChemistry/stempy/blob/afed0150d0444bf420ad57cfb41ff84128ee80ad/python/stempy/io/sparse_array.py#L773-L775). The rest of the function takes microseconds, but that part takes more than a second. I think that if we re-write those lines of code that re-number the scan positions, it should result in a significant performance increase and hopefully fix this issue.

**Comment by psavery** [comment]
@ercius I believe I have a good fix for this in #247. For one example where it took 1.5 seconds to perform the slicing, it now takes 4 microseconds.

If I re-generate your graphs that you have above, they are flat. So I believe this fixes it!

**Comment by psavery** [comment]
@ercius I actually found two places that needed to be fixed. Let me know if you are still planning to submit a PR, otherwise I can fix them up and submit one.

**Comment by psavery** [comment]
Hi @ercius. Thank you for sending the notebook! I took a look at it, but I thought that my changes in #248 might be easier to try. The reason is that the `SparseArray` class doesn't explicitly have a notion of whether something is being cropped, strided, indexed, etc. Instead, it takes the `slice()` objects (produced automatically from indexing/slicing the arrays), does a little manipulation (like unraveling the data), and then applies the slice objects directly to the numpy arrays. This allows numpy to figure out on its own what to do (cropping, striding, indexing, etc.).

This allows for more complex slicing on the `SparseArray`. For instance, you can do things like this:

```python
array[2:5, 0, ::-2]
array[3:21:3, :, :575]
```

And this complex slicing is taken care of automatically underneath by numpy.

Anyways, once we merge #248, do you mind giving it a try?

Those changes, however, won't be necessary anyways when we move to V3 for the SparseArray, since we will be removing the logic that manipulates scan positions (which appears to be the part that was causing the poor performance).

**Comment by psavery** [comment]
@ercius #248 is merged. I gave your notebook example a try with it, and it seemed to work well! I also tried doing a test crop that was very slow previously and it is now extremely fast.

Can you give it a try and let me know how it goes? It is on PyPI now as stempy 2.0.2.

**Comment by ercius** [comment]
Awesome! Ill give this a try soon and let you know.

**Comment by ercius** [comment]
I just got to look at this. Running my cropping notebook shows that your fix works perfectly.

**Comment by psavery** [comment]
@ercius Great, thanks Peter!
