### ISSUE TITLE
Upgrading python crashes on MPI counting with multipass reader

### ISSUE THREAD

**Issue by swelborn** [OpenChemistry/stempy#275]
Tracks issue raised in https://github.com/OpenChemistry/stempy/pull/274#issue-1532978275

issue stems from [this constructor](https://github.com/OpenChemistry/stempy/blob/d86c0a444fe0d8a3d68444b16fcefb03b7f1329e/python/image.cpp#L34-L47).

`vectorToPyArray()` function --> https://github.com/pybind/pybind11/issues/1042

Tried so far:
1. Upgraded pybind11 to latest version.

Things to try:
1. Consider https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types and https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#binding-stl-containers
2. Double-check serial version.

**Comment by swelborn** [comment]
See also: https://stackoverflow.com/questions/54876346/pybind11-and-stdvector-how-to-free-data-using-capsules

**Comment by psavery** [comment]
[This example](https://github.com/pybind/pybind11/issues/1042#issuecomment-647147819) from that issue, that someone else is using with apparent success, is very similar to [ours](https://github.com/OpenChemistry/stempy/blob/d86c0a444fe0d8a3d68444b16fcefb03b7f1329e/python/image.cpp#L21-L29) with just a few differences:

1. `static_cast` is used instead of `reinterpret_cast`
2. `py::array_t` is used instead of `py::array` (which also means they have to have the extra stride argument of `sizeof(T)` as well).

I'm not sure if either of those matter, but you could try it. 

You may also want to try acquiring the GIL [here](https://github.com/OpenChemistry/stempy/blob/d86c0a444fe0d8a3d68444b16fcefb03b7f1329e/python/image.cpp#L35), by adding `py::gil_scoped_acquire acquire;`.

**Comment by swelborn** [comment]
Submitted PR to fix this #288
