### ISSUE TITLE
Add support for processing data held in numpy array ( create from python )

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#60]
We currently have a reader that can read *.dat files in C++ and then provide a numpy view of the data. All our processing functions operate on this `Block` structure. We need to be able to process data from other source ( such as out HDF5 files ). Probably the simplest was to do this would be to support numpy arrays ( created in python ), we can then still use h5py for the reading. Ideally we would create a view of the memory used by the numpy array in the `Block` structure so we don't have to copy a bunch of memory around.

**Comment by wangzhezhe** [comment]
I think this could be implemented by two steps:
(1) Implementing the MemoryReader class which load image data from memory at cpp end
(2) Implementing the hdf5 python reader which send the numpy data to MemoryReader @cjh1

**Comment by psavery** [comment]
I'll leave a personal thought here that, whether the `Block` and `StreamReader` classes are re-used or not, I think it is very valuable to be able to read the data in chunks. Reading in chunks allows us to have one thread read in the data, while other threads process the data, so that processing and I/O can occur at the same time. 

It also allows us to avoid reading in the whole dataset at once, which is very useful since our datasets are large (sometimes >= 16 GB), which can be too large for some computers to have in memory at one time.

It might be worth considering re-using or generalizing the `Block` and `StreamReader` classes since reading and processing the data in chunks is already set up.

**Comment by cryos** [comment]
Yes, it is very important for us to be able to avoid reading in the entire data set. It would also be nice to be able to use Python to read in some of those chunks, so maybe we need to improve our Python interface to support implementing a stream reader in Python.

I think we still want a view into a NumPy array, but those arrays would be reading in chunks. We then need to communicate when the next chunk is needed. The alternative is to implement the HDF5 reader in C++, but I think we would miss out on the opportunity to offer a streaming reader interface.

**Comment by wangzhezhe** [comment]
Maybe I could try to implement a StreamReader based on hdf5 at python end, then we could consider how to make it compatible with the current code at cpp end. @cryos

**Comment by cryos** [comment]
Yes, if you develop some Python code to read blocks of images from the HDF5 format, then we can look at how we can call it when we want to load the next block of images. Make the number of images per block something that we can set.

**Comment by wangzhezhe** [comment]
please check this pull request https://github.com/OpenChemistry/stempy/pull/73

**Comment by cjh1** [comment]
This is now resolved
